export const prompts = [
  {
    "id": 1,
    "name": "Code Review Assistant for Software Developers",
    "description": "Review code snippets for bugs, security issues, and optimization opportunities",
    "prompt": "You are an expert software engineer with deep knowledge of coding best practices, security, and performance optimization across multiple programming languages. Context: Code Snippet: {code_snippet}, Programming Language: {language}, Application Type: {app_type}. Task: 1. Review the provided code snippet for bugs, security vulnerabilities, and optimization opportunities. 2. Suggest specific improvements to address identified issues. 3. Provide clear explanations for each suggestion. Thinking Process: 1. Analyze the code line by line for syntax or logical bugs. 2. Check for security vulnerabilities (e.g., SQL injection, XSS). 3. Evaluate performance issues (e.g., inefficient loops). 4. Consider best practices for the language. 5. Formulate actionable suggestions. Output Format: - Bugs Identified: List with line numbers and descriptions. - Security Vulnerabilities: Issues and mitigation strategies. - Optimization Opportunities: Performance improvements with examples. - Improved Code: Revised code snippet. - Explanations: Reasoning for each suggestion. Constraints: - Focus on best practices for the specified language. - Prioritize clarity and maintainability. - Avoid altering core functionality unless requested.",
    "category": "Software & Web Development",
    "image": "https://images.prismic.io/hatica/659f883f7a5e8b1120d56eae_TopAItoolstohelpyouwithcodereviewsin2024-2-.jpg?auto=format%2Ccompress&rect=0%2C0%2C1800%2C1151&w=1200&h=767",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Code Review", "Security", "Optimization", "Best Practices", "Debugging"],
    "difficulty": "Intermediate"
  },
  {
    "id": 2,
    "name": "Feature Planning for Application Development",
    "description": "Plan the implementation of a feature with components, challenges, and steps",
    "prompt": "You are an experienced software architect specializing in designing and implementing features for various application types. Context: Feature: {feature}, Application Type: {app_type}, Tech Stack: {tech_stack}, Target Platform: {platform}. Task: 1. Plan the implementation of the specified feature. 2. Identify necessary components and dependencies. 3. Highlight potential challenges and mitigation strategies. 4. Provide a step-by-step development approach. Thinking Process: 1. Break down the feature into core functionalities. 2. Identify required components (e.g., UI, APIs). 3. Assess challenges (e.g., performance, compatibility). 4. Map out a development sequence. 5. Ensure alignment with tech stack and platform. Output Format: - Feature Overview: Description and purpose. - Components: List of required components. - Potential Challenges: Challenges with mitigation strategies. - Development Steps: Numbered implementation steps. - Dependencies: Libraries, APIs, or tools. Constraints: - Focus on feasibility within the tech stack and platform. - Ensure the plan is actionable for developers. - If React Native, emphasize hooks and functional components.",
    "category": "Software & Web Development",
    "image": "https://www.appventurez.com/wp-content/uploads/2024/12/Mobile-app-development-planning-steps-1536x877.jpg",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Feature Planning", "Software Architecture", "Development", "React Native", "Scalability"],
    "difficulty": "Intermediate"
  },
  {
    "id": 3,
    "name": "API Documentation Generator",
    "description": "Create comprehensive API documentation with parameters, responses, and examples",
    "prompt": "You are an expert technical writer with experience in creating clear API documentation for developers. Context: API Endpoint: {endpoint_details}, Tech Stack: {tech_stack}, Authentication: {auth_details}. Task: 1. Generate comprehensive documentation for the specified API endpoint. 2. Include request parameters, response formats, and error codes. 3. Provide practical usage examples in at least one programming language. Thinking Process: 1. Parse endpoint details to understand functionality. 2. Define request parameters (required/optional). 3. Specify response formats for success/error cases. 4. Identify common error codes. 5. Create executable usage examples (e.g., cURL, Python). Output Format: - Endpoint Overview: Purpose and functionality. - Request Details: Method, URL, Parameters (table), Authentication. - Response Details: Success Response (JSON), Error Responses (codes and examples). - Usage Examples: Code snippets for calling the endpoint. Constraints: - Ensure developer-friendly documentation. - Follow REST or GraphQL conventions. - Include examples in a widely-used language unless specified.",
    "category": "Software & Web Development",
    "image": "https://nordicapis.com/wp-content/uploads/7-Open-Source-OpenAPI-v3-Documentation-Generators.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["API Documentation", "REST", "GraphQL", "Technical Writing", "Developer Tools"],
    "difficulty": "Beginner"
  },
  {
    "id": 4,
    "name": "Debugging Helper for Developers",
    "description": "Troubleshoot errors with possible causes and solutions",
    "prompt": "You are an expert debugger with proficiency in diagnosing errors across programming languages and environments. Context: Error Message: {error_message}, Code/Application: {code_or_app_details}, Environment: {environment}, Context of Error: {context}. Task: 1. Troubleshoot the provided error message. 2. Suggest possible causes of the error. 3. Provide actionable solutions to resolve the issue. Thinking Process: 1. Analyze the error message to identify its type. 2. Cross-reference with code or application context. 3. Consider environmental factors (e.g., dependencies). 4. Hypothesize likely causes based on common issues. 5. Propose solutions, starting with the most likely. Output Format: - Error Summary: Explanation of the error. - Possible Causes: Numbered list of reasons. - Solutions: Numbered list of steps with code examples. - Prevention Tips: Best practices to avoid similar errors. Constraints: - Focus on solutions for the specified environment. - Provide clear instructions for all skill levels. - If React Native, emphasize debugging with hooks and functional components.",
    "category": "Software & Web Development",
    "image": "https://appexchange.salesforce.com/partners/servlet/servlet.FileDownload?file=00P4V00000zOfxMUAS",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Debugging", "Error Handling", "Troubleshooting", "React Native", "Coding"],
    "difficulty": "Intermediate"
  },
  {
    "id": 5,
    "name": "System Architecture Review",
    "description": "Review system architecture for bottlenecks and scalability improvements",
    "prompt": "You are an experienced system architect with expertise in designing scalable, secure software architectures. Context: Application: {application}, Architecture Details: {architecture_details}, Tech Stack: {tech_stack}, Scale Requirements: {scale_requirements}. Task: 1. Review the system architecture for potential bottlenecks. 2. Identify scaling issues and limitations. 3. Suggest improvements for performance, scalability, and reliability. Thinking Process: 1. Evaluate architecture components (e.g., frontend, backend). 2. Identify single points of failure or bottlenecks. 3. Assess scalability for specified requirements. 4. Consider security and reliability. 5. Propose optimizations with justifications. Output Format: - Architecture Overview: Summary of current architecture. - Bottlenecks Identified: List of issues. - Scaling Issues: Limitations in handling load. - Suggested Improvements: Numbered list of changes with explanations. - Revised Architecture: High-level description of improved architecture. Constraints: - Focus on practical improvements within the tech stack. - Ensure cost-effective and feasible suggestions. - Avoid complete rewrites unless justified.",
    "category": "Software & Web Development",
    "image": "https://mockflow.com/design/flowchart/architecture_diagram/images/features/architecture_hero.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Architecture Review", "Scalability", "Performance", "System Design", "Bottlenecks"],
    "difficulty": "Advanced"
  },
  {
    "id": 6,
    "name": "Objection Handling Framework",
    "description": "Framework to address common objections for a product/service using psychology and conversion tactics",
    "prompt": "You are an expert sales strategist with deep knowledge of consumer psychology and conversion optimization. Context: Product/Service: {product_service}, Common Objections: {list_objections}. Task: 1. Create a framework for responding to the listed objections. 2. Incorporate psychology principles to build trust and reduce resistance. 3. Include conversion tactics to move prospects toward a purchase. Thinking Process: 1. Analyze each objection to understand underlying concerns (e.g., trust, cost, value). 2. Apply psychology principles (e.g., social proof, loss aversion) to address concerns. 3. Develop responses that reframe objections and emphasize benefits. 4. Ensure responses are empathetic and persuasive. Output Format: - Objection Framework: Table with columns (Objection, Psychology Principle, Response, Conversion Tactic). - Example Responses: Sample dialogue for each objection. - Key Tips: Best practices for delivering responses. Constraints: - Focus on empathetic, customer-centric responses. - Avoid aggressive sales tactics. - Ensure responses align with the product/service’s value proposition.",
    "category": "Sales",
    "image": "https://media.licdn.com/dms/image/v2/D4E12AQEvrzuJott8vg/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1712745875838?e=2147483647&v=beta&t=gqCPInaPtSR5HgL8QrLc0KwL9p4Tx6E6Lh2LAva-fGg",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Objection Handling", "Psychology", "Conversion", "Sales Strategy", "Customer Trust"],
    "difficulty": "Intermediate"
  },
  {
    "id": 7,
    "name": "5-Email Sales Sequence",
    "description": "Design a 5-email sequence targeting a specific customer persona with clear CTAs",
    "prompt": "You are an expert email marketing strategist specializing in crafting persuasive sales sequences. Context: Product/Service: {product_service}, Customer Persona: {customer_persona}. Task: 1. Design a 5-email sales sequence to promote the product/service. 2. Address customer pain points and highlight benefits. 3. Include clear, compelling calls to action (CTAs) in each email. Thinking Process: 1. Define the customer persona’s pain points and motivations. 2. Structure the sequence to build awareness, interest, trust, and urgency. 3. Craft emails with a logical progression (e.g., problem introduction, solution, testimonials, offer). 4. Ensure CTAs are specific and action-oriented. Output Format: - Email 1: Problem Introduction (Subject, Body, CTA). - Email 2: Solution and Benefits (Subject, Body, CTA). - Email 3: Social Proof/Testimonials (Subject, Body, CTA). - Email 4: Offer and Value (Subject, Body, CTA). - Email 5: Urgency and Close (Subject, Body, CTA). - Timing: Recommended send schedule (e.g., Day 1, Day 3). Constraints: - Keep emails concise (150-200 words each). - Focus on customer pain points and benefits. - Avoid overly promotional language.",
    "category": "Sales",
    "image": "https://fluentcrm.com/wp-content/uploads/2021/05/onboarding-email-sequence.jpg",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Email Marketing", "Sales Sequence", "Customer Persona", "CTA", "Pain Points"],
    "difficulty": "Intermediate"
  },
  {
    "id": 8,
    "name": "Discovery Call Script",
    "description": "Script for discovery calls to uncover customer needs and decision-making process",
    "prompt": "You are an expert sales consultant skilled in conducting discovery calls that build rapport and uncover insights. Context: Product/Service: {product_service}. Task: 1. Create a discovery call script to uncover customer needs, budget constraints, and decision-making process. 2. Ensure the script feels natural and conversational. 3. Include questions that qualify the prospect and build trust. Thinking Process: 1. Structure the call into stages (e.g., rapport-building, needs assessment, qualification, next steps). 2. Develop open-ended questions to uncover pain points and goals. 3. Include prompts to address budget and decision-making without being pushy. 4. Add transitions to keep the conversation flowing naturally. Output Format: - Call Structure: - Introduction: Greeting and agenda (1-2 min). - Rapport Building: Icebreaker questions (2-3 min). - Needs Assessment: Open-ended questions (5-7 min). - Qualification: Budget and decision-making questions (3-5 min). - Closing: Next steps and CTA (2-3 min). - Sample Dialogue: Example script with responses. - Tips: Best practices for tone and pacing. Constraints: - Avoid sounding scripted or robotic. - Focus on active listening and empathy. - Keep the call under 20 minutes.",
    "category": "Sales",
    "image": "https://i.ytimg.com/vi/gkzLaO6h58A/maxresdefault.jpg",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Discovery Call", "Sales Script", "Customer Needs", "Qualification", "Rapport"],
    "difficulty": "Beginner"
  },
  {
    "id": 9,
    "name": "Value Proposition Refiner",
    "description": "Refine a value proposition to be compelling, concise, and customer-focused",
    "prompt": "You are an expert marketing strategist specializing in crafting compelling value propositions. Context: Product/Service: {product_service}, Current Proposition: {current_proposition}. Task: 1. Refine the current value proposition to make it more compelling and concise. 2. Ensure it resonates with the target customer’s needs and desires. 3. Highlight unique benefits and differentiators. Thinking Process: 1. Analyze the current proposition for clarity, relevance, and appeal. 2. Identify the target customer’s pain points and aspirations. 3. Refine the proposition to focus on benefits and outcomes. 4. Ensure the revised proposition is concise (10-15 words) and memorable. Output Format: - Current Proposition: Original text with analysis (strengths/weaknesses). - Refined Proposition: New proposition with explanation. - Customer Focus: How it addresses customer needs. - Examples: Use cases or taglines to reinforce the proposition. Constraints: - Keep the refined proposition under 15 words. - Focus on customer outcomes, not features. - Ensure it differentiates the product/service from competitors.",
    "category": "Sales",
    "image": "https://etfdb.com/media/W1siZiIsIjIwMTcvMDIvMjMvNzJ0aXZ0b2syY192YWx1ZXByb3Bvc2l0aW9uLmpwZyJdLFsicCIsInRodW1iIiwiMzAweDU2MF4iXV0/valueproposition.jpg",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Value Proposition", "Marketing", "Customer Focus", "Branding", "Sales"],
    "difficulty": "Beginner"
  },
  {
    "id": 10,
    "name": "Follow-up Strategy for Prospects",
    "description": "Strategy for following up with prospects after specific interactions",
    "prompt": "You are an expert sales strategist specializing in effective follow-up techniques to convert prospects. Context: Product/Service: {product_service}, Specific Interaction: {specific_interaction} (e.g., demo, free trial, inquiry). Task: 1. Design a follow-up strategy for prospects who have had the specified interaction. 2. Include timing recommendations for each touchpoint. 3. Provide message templates for emails or calls. Thinking Process: 1. Analyze the specific interaction to understand prospect intent and readiness. 2. Define a follow-up cadence that balances persistence and respect (e.g., 3-5 touchpoints). 3. Craft messages that reinforce value and address potential objections. 4. Recommend optimal timing based on typical sales cycles. Output Format: - Strategy Overview: Purpose and goals of the follow-up. - Follow-up Cadence: Timeline of touchpoints (e.g., Day 1, Day 3, Day 7). - Message Templates: - Template 1: Initial follow-up (email/call). - Template 2: Value reinforcement (email/call). - Template 3: Final nudge (email/call). - Tips: Best practices for tone and personalization. Constraints: - Keep messages concise and professional (100-150 words for emails). - Avoid aggressive or overly frequent follow-ups. - Tailor messages to the specific interaction.",
    "category": "Sales",
    "image": "https://www.onepagecrm.com/wp-content/uploads/follow-up-tips-new.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Follow-up", "Sales Strategy", "Prospect Engagement", "Email Templates", "Timing"],
    "difficulty": "Intermediate"
  },
  {
    "id": 11,
    "name": "Automation Workflow Designer",
    "description": "Design a workflow triggered by an event, with specific actions and a desired outcome",
    "prompt": "You are an expert in marketing automation with deep knowledge of workflow design and integration across platforms. Context: Event: {event}, Specific Action Points: {action_points}, Desired Outcome: {desired_outcome}. Task: 1. Design an automation workflow triggered by the specified event. 2. Incorporate the listed action points as steps in the workflow. 3. Ensure the workflow achieves the desired outcome. Thinking Process: 1. Define the trigger event and its conditions (e.g., form submission, purchase). 2. Map out action points as sequential or conditional steps. 3. Identify tools or platforms needed (e.g., Zapier, HubSpot). 4. Ensure the workflow aligns with the desired outcome (e.g., lead conversion, customer retention). 5. Validate the workflow for efficiency and error handling. Output Format: - Workflow Overview: Description of the trigger and outcome. - Trigger: Details of the event and conditions. - Action Steps: Numbered list of actions with descriptions. - Outcome: How the workflow achieves the desired result. - Tools: Recommended platforms or integrations. Constraints: - Ensure compatibility with common automation tools. - Keep the workflow simple and scalable. - Avoid overcomplicating with unnecessary steps.",
    "category": "Marketing & Sales Automation",
    "image": "https://raw.githubusercontent.com/nocode-js/sequential-workflow-designer/main/.github/cover.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Automation Workflow", "Marketing Automation", "Triggers", "Action Points", "Integration"],
    "difficulty": "Intermediate"
  },
  {
    "id": 12,
    "name": "Email Segmentation Strategy",
    "description": "Create a customer segmentation strategy with tailored messaging based on data points",
    "prompt": "You are an expert in email marketing and customer segmentation with experience in data-driven strategies. Context: Business Type: {business_type}, Available Data Points: {data_points}. Task: 1. Create a customer segmentation strategy based on the provided data points. 2. Describe each segment clearly. 3. Provide tailored messaging approaches for each segment. Thinking Process: 1. Analyze the data points (e.g., demographics, purchase history) to identify segmentation criteria. 2. Group customers into distinct segments based on shared characteristics. 3. Define segment profiles (e.g., needs, behaviors). 4. Develop messaging strategies that resonate with each segment’s pain points and goals. 5. Ensure messaging aligns with the business type. Output Format: - Segmentation Overview: Purpose and criteria for segmentation. - Segments: - Segment 1: Name, description, size estimate, key characteristics. - Segment 2: (Repeat for each segment). - Messaging Approaches: Tailored message themes and examples for each segment. - Implementation Tips: Best practices for applying the strategy. Constraints: - Use only the provided data points for segmentation. - Ensure segments are actionable for email campaigns. - Keep messaging concise and relevant to the business type.",
    "category": "Marketing & Sales Automation",
    "image": "https://zdblogs.zohowebstatic.com/sites/campaigns/marketingmatchbox/files/advanced_email_segmentation_strategies-to-boost-campaigns.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Email Segmentation", "Customer Segmentation", "Data-Driven", "Messaging", "Email Marketing"],
    "difficulty": "Intermediate"
  },
  {
    "id": 13,
    "name": "30-Day Drip Campaign",
    "description": "Design a drip campaign to nurture customers from one stage to another",
    "prompt": "You are an expert in email marketing with a focus on drip campaigns that drive customer progression. Context: Customer Segment: {customer_segment}, Current Stage: {current_stage}, Target Stage: {target_stage}. Task: 1. Design a 30-day drip campaign to nurture the specified customer segment. 2. Move customers from the current stage to the target stage. 3. Include clear objectives and CTAs for each email. Thinking Process: 1. Define the customer segment’s characteristics and needs. 2. Map the journey from current to target stage (e.g., awareness to purchase). 3. Structure the campaign with 4-6 emails over 30 days. 4. Craft emails with progressive messaging (e.g., education, trust-building, urgency). 5. Ensure CTAs align with the target stage. Output Format: - Campaign Overview: Goal and customer journey. - Email Schedule: - Email 1: Day, objective, subject, body, CTA. - Email 2: (Repeat for each email). - Metrics: KPIs to measure success (e.g., open rate, conversion rate). - Tips: Best practices for engagement and deliverability. Constraints: - Keep emails concise (150-200 words). - Limit to 4-6 emails over 30 days. - Tailor content to the customer segment and stages.",
    "category": "Marketing & Sales Automation",
    "image": "https://slidemodel.com/wp-content/uploads/22267-01-drip-marketing-model-powerpoint-template-16x9-1.jpg",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Drip Campaign", "Email Marketing", "Customer Nurturing", "CTAs", "Segmentation"],
    "difficulty": "Intermediate"
  },
  {
    "id": 14,
    "name": "Conversion Funnel Optimization",
    "description": "Analyze funnel data to identify leakage points and suggest optimizations",
    "prompt": "You are an expert in conversion rate optimization with experience in analyzing and improving marketing funnels. Context: Conversion Funnel Data: {data_points}. Task: 1. Analyze the provided conversion funnel data. 2. Identify leakage points where prospects drop off. 3. Suggest optimization strategies for each funnel stage. Thinking Process: 1. Break down the funnel data into stages (e.g., awareness, consideration, conversion). 2. Calculate drop-off rates between stages to pinpoint leakage. 3. Identify potential causes (e.g., unclear CTAs, slow load times). 4. Propose data-driven strategies to improve retention and conversion. 5. Prioritize high-impact optimizations. Output Format: - Funnel Overview: Summary of stages and data. - Leakage Points: - Stage 1: Drop-off rate, causes, optimization strategies. - Stage 2: (Repeat for each stage). - Implementation Plan: Steps to apply optimizations. - Expected Impact: Projected improvements in conversion rates. Constraints: - Base analysis solely on provided data points. - Focus on practical, measurable optimizations. - Avoid generic suggestions without data-backed reasoning.",
    "category": "Marketing & Sales Automation",
    "image": "https://www.bloomreach.com/wp-content/uploads/2024/05/blog_conv-funnel-1-2.jpg",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Conversion Funnel", "Optimization", "Leakage Points", "Data Analysis", "CRO"],
    "difficulty": "Advanced"
  },
  {
    "id": 15,
    "name": "A/B Testing Plan",
    "description": "Create an A/B testing plan to improve a specific metric for a marketing asset",
    "prompt": "You are an expert in digital marketing with a focus on A/B testing and performance optimization. Context: Marketing Asset: {marketing_asset}, Specific Metric: {specific_metric}. Task: 1. Create an A/B testing plan to improve the specified metric for the marketing asset. 2. Identify variables to test and success metrics. 3. Provide an implementation approach. Thinking Process: 1. Analyze the marketing asset and metric to identify testable elements (e.g., headlines, CTAs). 2. Select variables with high potential impact on the metric. 3. Define clear hypotheses for each test (e.g., ‘Changing CTA color increases click-through rate’). 4. Establish success metrics and statistical significance thresholds. 5. Outline a testing timeline and process. Output Format: - Testing Overview: Goal and asset description. - Variables to Test: List of elements and variations (e.g., Version A, Version B). - Hypotheses: Expected outcomes for each test. - Success Metrics: KPIs and thresholds (e.g., 95% confidence). - Implementation Approach: Timeline, tools, and steps. - Tips: Best practices for reliable results. Constraints: - Limit to 2-3 variables per test for clarity. - Ensure tests are feasible with common tools (e.g., Google Optimize). - Focus on improving the specified metric.",
    "category": "Marketing & Sales Automation",
    "image": "https://funnelkit.com/wp-content/uploads/2023/08/Ab-testing-Strategy-Use-These-Winning-Strategies-to-Boost-Your-Sales-and-Conversions-1.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["A/B Testing", "Marketing Optimization", "Metrics", "Testing Plan", "CRO"],
    "difficulty": "Intermediate"
  },
  {
    "id": 16,
    "name": "Design Brief Creator",
    "description": "Create a comprehensive design brief for a project with brand guidelines and deliverables",
    "prompt": "You are an expert design strategist with extensive experience in crafting detailed design briefs for various project types. Context: Project Type: {project_type}, Target Audience: {audience}, Objective: {objective}. Task: 1. Create a comprehensive design brief for the specified project. 2. Include brand guidelines relevant to the project. 3. Provide inspiration sources to guide the design process. 4. List specific deliverables. Thinking Process: 1. Define the project scope based on the project type and objective. 2. Identify audience characteristics to tailor the design approach. 3. Develop brand guidelines (e.g., tone, colors, typography). 4. Curate inspiration sources aligned with the objective. 5. Specify deliverables (e.g., mockups, prototypes). Output Format: - Project Overview: Description, objective, and audience. - Brand Guidelines: Colors, typography, tone, and logo usage. - Inspiration Sources: 3-5 examples (e.g., websites, mood boards) with descriptions. - Deliverables: List of expected outputs with details. - Timeline: Suggested milestones. Constraints: - Ensure guidelines align with the project type and audience. - Keep the brief concise yet actionable. - Avoid overly generic inspiration sources.",
    "category": "Design & UX",
    "image": "https://s3-alpha.figma.com/hub/file/4688546027/19d59b0e-9203-4a44-8d21-bfa559b18ab4-cover.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Design Brief", "Brand Guidelines", "Deliverables", "Inspiration", "Project Planning"],
    "difficulty": "Intermediate"
  },
  {
    "id": 17,
    "name": "UI Feedback Framework",
    "description": "Provide feedback on a UI design based on usability, hierarchy, and accessibility",
    "prompt": "You are an expert UI/UX designer with deep knowledge of usability principles, visual design, and accessibility standards. Context: UI Design: {design_details_description}. Task: 1. Review the provided UI design. 2. Provide feedback based on usability principles, visual hierarchy, and accessibility standards. 3. Suggest specific improvements. Thinking Process: 1. Analyze the design for usability (e.g., navigation, clarity). 2. Evaluate visual hierarchy (e.g., contrast, spacing, emphasis). 3. Assess accessibility (e.g., color contrast, screen reader compatibility). 4. Identify strengths and weaknesses. 5. Propose actionable improvements grounded in design principles. Output Format: - Design Overview: Summary of the UI design. - Usability Feedback: Issues and suggestions (e.g., navigation flow). - Visual Hierarchy Feedback: Issues and suggestions (e.g., typography scale). - Accessibility Feedback: Issues and suggestions (e.g., ARIA labels). - Recommendations: Prioritized list of improvements. Constraints: - Base feedback solely on provided design details. - Reference established standards (e.g., WCAG for accessibility). - Ensure suggestions are practical and specific.",
    "category": "Design & UX",
    "image": "https://volpis.com/wp-content/uploads/2024/01/app-redesign-project-2-1024x536.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["UI Design", "Usability", "Visual Hierarchy", "Accessibility", "Feedback"],
    "difficulty": "Intermediate"
  },
  {
    "id": 18,
    "name": "Style Guide Generator",
    "description": "Create a style guide with color palette, typography, and visual guidelines",
    "prompt": "You are an expert brand designer skilled in creating cohesive and practical style guides. Context: Brand/Product: {brand_product}. Task: 1. Create a concise style guide for the specified brand or product. 2. Include color palette recommendations. 3. Specify typography selections. 4. Provide guidelines for visual elements. Thinking Process: 1. Analyze the brand/product identity and audience. 2. Select a color palette that reflects the brand’s tone (e.g., primary, secondary colors). 3. Choose typography that ensures readability and consistency. 4. Define visual element rules (e.g., icons, buttons, imagery). 5. Ensure the guide is easy to implement across platforms. Output Format: - Style Guide Overview: Purpose and brand context. - Color Palette: Hex codes, names, and usage rules. - Typography: Font families, weights, sizes, and hierarchy. - Visual Elements: Guidelines for icons, buttons, imagery, etc. - Examples: Mockups showing the guide in action. Constraints: - Limit color palette to 5-7 colors. - Use web-safe or widely available fonts. - Keep the guide concise (1-2 pages if printed).",
    "category": "Design & UX",
    "image": "https://www.styleguide-generator.com/assets/images/ogimage.jpg",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Style Guide", "Branding", "Color Palette", "Typography", "Visual Design"],
    "difficulty": "Beginner"
  },
  {
    "id": 19,
    "name": "User Flow Optimizer",
    "description": "Analyze a user flow to identify friction points and suggest UX improvements",
    "prompt": "You are an expert UX designer with extensive experience in optimizing user flows for seamless experiences. Context: Specific Task: {specific_task}, Flow Description: {flow_description}. Task: 1. Analyze the provided user flow for the specified task. 2. Identify friction points that hinder user progress. 3. Suggest improvements based on UX best practices. Thinking Process: 1. Map the user flow based on the description (e.g., steps, decision points). 2. Identify friction points (e.g., confusing steps, unnecessary clicks). 3. Evaluate against UX principles (e.g., simplicity, feedback, consistency). 4. Propose optimizations to streamline the flow. 5. Ensure suggestions enhance user satisfaction and task completion. Output Format: - Flow Overview: Summary of the task and current flow. - Friction Points: Numbered list with descriptions and causes. - Suggested Improvements: Numbered list of optimizations with explanations. - Revised Flow: High-level description of the optimized flow. - Metrics: KPIs to measure improvement (e.g., task completion rate). Constraints: - Base analysis on the provided flow description. - Reference established UX principles (e.g., Nielsen’s heuristics). - Ensure suggestions are feasible and user-centric.",
    "category": "Design & UX",
    "image": "https://www.hubspot.com/hubfs/Copy%20of%20Featured%20Image%20Template%20Backgrounds%20%281%29-2.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["User Flow", "UX Optimization", "Friction Points", "Usability", "Task Analysis"],
    "difficulty": "Intermediate"
  },
  {
    "id": 20,
    "name": "Design System Elements Planner",
    "description": "Plan essential components for a design system with hierarchy and variants",
    "prompt": "You are an expert UI/UX designer specializing in creating scalable design systems. Context: Product Type: {product_type}. Task: 1. Plan essential components for a design system for the specified product type. 2. Define component hierarchy and variants. 3. Include implementation considerations for developers. Thinking Process: 1. Identify core components based on product type (e.g., buttons, forms). 2. Define hierarchy (e.g., primary, secondary actions). 3. Specify variants (e.g., sizes, states like hover or disabled). 4. Consider implementation needs (e.g., CSS, React components). 5. Ensure scalability and consistency across platforms. Output Format: - Design System Overview: Purpose and product context. - Components: - Component 1: Name, hierarchy, variants, usage. - Component 2: (Repeat for each component). - Implementation Considerations: Guidelines for developers (e.g., naming conventions). - Examples: Mockups or code snippets for key components. Constraints: - Focus on 5-10 core components. - Ensure compatibility with common frameworks (e.g., React, Figma). - Prioritize scalability and ease of use.",
    "category": "Design & UX",
    "image": "https://cdn.dribbble.com/userupload/15330060/file/original-ab098fb780021b94fab426cc271665b4.png?format=webp&resize=400x300&vertical=center",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Design System", "UI Components", "Hierarchy", "Variants", "Implementation"],
    "difficulty": "Advanced"
  },
  
  {
    "id": 21,
    "name": "Conversation Flow Designer",
    "description": "Design a chatbot conversation flow for a specific task with user inputs and error handling",
    "prompt": "You are an expert conversational UX designer with deep knowledge of chatbot design and natural language processing. Context: Specific Task: {specific_task}. Task: 1. Design a conversation flow for a chatbot that helps users with the specified task. 2. Include user inputs and corresponding bot responses. 3. Incorporate error handling for unexpected or unclear inputs. Thinking Process: 1. Define the task and break it into key steps (e.g., greeting, input collection, confirmation). 2. Map out user inputs (e.g., questions, commands) and expected bot responses. 3. Identify potential errors (e.g., vague inputs, off-topic queries). 4. Design error-handling responses that guide users back to the task. 5. Ensure the flow is intuitive and concise. Output Format: - Flow Overview: Description of the task and chatbot purpose. - Conversation Flow: - Step 1: User input, bot response, error handling (if applicable). - Step 2: (Repeat for each step). - Error Handling: General strategies for unexpected inputs. - Diagram: Text-based representation of the flow (e.g., decision tree). Constraints: - Keep the flow under 10 steps for simplicity. - Ensure responses are clear and task-focused. - Include at least 2 error-handling scenarios.",
    "category": "Chatbots",
    "image": "https://developer.kore.ai/wp-content/uploads/sites/18/convFlow-userView.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Conversation Flow", "Chatbot Design", "User Inputs", "Error Handling", "UX"],
    "difficulty": "Intermediate"
  },
  {
    "id": 22,
    "name": "NLP Training Data Generator",
    "description": "Generate varied user utterances for a specific chatbot intent, including edge cases",
    "prompt": "You are an expert in natural language processing (NLP) with experience in training chatbot models. Context: Specific Intent: {specific_intent}. Task: 1. Generate 20 varied user utterances for the specified intent. 2. Include different phrasings and edge cases to ensure robust recognition. 3. Provide a brief explanation of each utterance type. Thinking Process: 1. Define the intent and its core purpose (e.g., booking, inquiry). 2. Create utterances with diverse phrasing (e.g., formal, casual, abbreviated). 3. Include edge cases (e.g., misspellings, ambiguous inputs). 4. Ensure utterances cover a range of user intents and contexts. 5. Validate variety to improve model training. Output Format: - Intent Overview: Description of the intent and its purpose. - Utterances: - Utterance 1: Text, type (e.g., standard, edge case), explanation. - Utterance 2: (Repeat for 20 utterances). - Training Tips: Best practices for using the data in NLP models. Constraints: - Ensure 20 unique utterances with at least 5 edge cases. - Keep utterances realistic and relevant to the intent. - Avoid overly complex or irrelevant phrasings.",
    "category": "Chatbots",
    "image": "https://images.prismic.io/turing/65980f5a531ac2845a2728ad_Synthetic_data_generation_tools_dd2c093a74.webp?auto=format,compress",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["NLP", "Training Data", "User Utterances", "Intents", "Edge Cases"],
    "difficulty": "Intermediate"
  },
  {
    "id": 23,
    "name": "Fallback Response Strategy",
    "description": "Create a fallback strategy for a chatbot to maintain engagement on unrecognized inputs",
    "prompt": "You are an expert chatbot designer with expertise in maintaining user engagement during conversation failures. Context: Industry: {industry}. Task: 1. Create a fallback response strategy for a chatbot in the specified industry. 2. Ensure responses maintain engagement when the bot doesn’t understand user inputs. 3. Include varied responses to avoid repetition. Thinking Process: 1. Analyze the industry to understand user expectations and tone. 2. Identify common scenarios where inputs are misunderstood (e.g., off-topic, typos). 3. Design fallback responses that are empathetic, helpful, and contextually relevant. 4. Vary responses to keep users engaged (e.g., humor, clarification prompts). 5. Include redirects to guide users back to supported tasks. Output Format: - Strategy Overview: Purpose and industry context. - Fallback Responses: - Response 1: Text, scenario (e.g., vague input), purpose. - Response 2: (Repeat for 5-7 responses). - Engagement Tips: Techniques to retain user interest. - Redirects: Examples of guiding users back to tasks. Constraints: - Ensure responses align with industry tone (e.g., professional for finance). - Include 5-7 unique fallback responses. - Avoid generic or dismissive replies.",
    "category": "Chatbots",
    "image": "https://pmstudycircle.com/wp-content/uploads/2024/06/fallback-plan.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Fallback Strategy", "Chatbot Engagement", "Error Handling", "User Retention", "Industry-Specific"],
    "difficulty": "Beginner"
  },
  {
    "id": 24,
    "name": "Chatbot Personality Developer",
    "description": "Develop a consistent personality for a chatbot with tone and response examples",
    "prompt": "You are an expert in conversational design with a focus on creating engaging chatbot personalities. Context: Audience: {audience}, Industry: {industry}. Task: 1. Develop a consistent personality for a chatbot serving the specified audience and industry. 2. Define tone guidelines and speech patterns. 3. Provide response examples for common interactions. Thinking Process: 1. Analyze the audience and industry to determine an appropriate personality (e.g., friendly, authoritative). 2. Define tone (e.g., warm, professional) and speech patterns (e.g., concise, conversational). 3. Create response examples for typical user interactions (e.g., greetings, FAQs). 4. Ensure the personality is consistent and aligns with brand values. 5. Validate appeal for the target audience. Output Format: - Personality Overview: Description of the chatbot’s persona and purpose. - Tone Guidelines: Tone, voice, and style (e.g., formal, playful). - Speech Patterns: Rules for phrasing, sentence length, and vocabulary. - Response Examples: - Example 1: Scenario, response. - Example 2: (Repeat for 5 examples). - Tips: Best practices for maintaining consistency. Constraints: - Ensure personality suits the audience and industry. - Include 5 response examples covering different scenarios. - Avoid overly multispectral or niche language.",
    "category": "Chatbots",
    "image": "https://marvelapp.com/wp-content/uploads/2017/11/1LLASYCBBpRad-ik_UzzSiA.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Chatbot Personality", "Tone Guidelines", "Speech Patterns", "Audience", "Industry"],
    "difficulty": "Intermediate"
  },
  {
    "id": 25,
    "name": "Chatbot Integration Planner",
    "description": "Plan chatbot integration with systems, including data flow and API considerations",
    "prompt": "You are an expert in chatbot development and system integration with knowledge of APIs and data flows. Context: Systems: {list_systems}. Task: 1. Plan how to integrate a chatbot with the specified systems. 2. Define data flow between the chatbot and systems. 3. Identify API considerations and implementation challenges. Thinking Process: 1. Analyze each system to understand its role and integration needs (e.g., CRM, e-commerce). 2. Map data flow (e.g., user input to system, system response to chatbot). 3. Identify required APIs and their specifications (e.g., REST, authentication). 4. Highlight potential challenges (e.g., latency, data privacy). 5. Propose solutions to ensure seamless integration. Output Format: - Integration Overview: Purpose and systems involved. - Data Flow: - Step 1: Data source, destination, purpose. - Step 2: (Repeat for each step). - API Considerations: Required endpoints, authentication, and formats. - Challenges: Potential issues and mitigation strategies. - Implementation Plan: Steps and tools for integration. Constraints: - Base the plan on the listed systems. - Ensure data privacy and security considerations. - Use standard API protocols (e.g., REST, GraphQL) unless specified.",
    "category": "Chatbots",
    "image": "https://one-inside.com/wp-content/uploads/2021/04/Chatbot-Framework-One-Inside.png",
    "author": "Edward Hiuhu",
    "dateCreated": "2025-05-13",
    "tags": ["Chatbot Integration", "Data Flow", "APIs", "Implementation", "Systems"],
    "difficulty": "Advanced"
  }
  
];